### ISSUE TITLE
[TODO] Documentation and help resources

### ISSUE THREAD

**Issue by apreshill** [rstudio/revealjs#98]
- [ ] Add a tag on RStudio Community for questions
- [ ] Build a new pkgdown site
- [ ] hex sticker
- [ ] add pkgdown site to pkgs.rstudio.com/revealjs
